version: "3"
services:
  circular_dependency:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: circular_dependency-image
    container_name: circular_dependency-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
